name: Cleanup Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ["run-bot.yml"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - name: Run cleanup script
      env:
        REPO: ${{ github.repository }}
        TOKEN: ${{ secrets.GTOKEN }}
      run: python cleanup_workflow_runs.py

    - name: Commit and Push Logs
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add logs.json
        git commit -m "Update cleanup logs"
        git push
